imageresizer:
  build: .
  #image: monster1025/imageresizer
  container_name: imageresizer
  restart: always
  volumes: 
    - "./img:/img"
  environment:
    - MAX_IMG_FILE_SIZE=1500
    - QUALITY=90
    - DIVIDE_SIZE=90
    - FOLDER=./img/
    - SLEEP=5